### ISSUE TITLE
新版本的 To-Do list

### ISSUE THREAD

**Issue by jaxvanyang** [zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system#19]
感觉可以开一个 issue 或 project 收集 23 届同学在使用中碰到的问题，然后整理出一个 To-Do list，全部完成后可以发布新的版本。

每个老师标准不同，我有一些比较个人的小调整，这几天会整理一下尝试 PR。

- [x] #12 尝试修复下
- [x] #9 没必要的话就 close as not planned
- [x] 更新 Makefile，定义宏来编译 latex 文件，简化规则
- [x] 更新 README，添加一般的编译方式
- [x] 在源文件注释和手册中添加非 Windows 用户安装所需字体的方法
- [x] #13 优化目录结构

**Comment by Zewbiee** [comment]
这个可以有。

另外我想最好能开一个长理latex模板专用账号，把毕业论文模板和beamer模板分成两个独立的仓库，这样显得比较“官方”，也方便维护和交接，你觉得怎么样？

**Comment by jaxvanyang** [comment]
> 这个可以有。
> 
> 另外我想最好能开一个长理latex模板专用账号，把毕业论文模板和beamer模板分成两个独立的仓库，这样显得比较“官方”，也方便维护和交接，你觉得怎么样？

感觉挺不错的，可以搞个组织，叫 CSUST LaTeX SIG 之类的，也可以吸引长理的 LaTeX 用户。

**Comment by jaxvanyang** [comment]
我列了下我想进行的更新，麻烦学长看下哪些可以进行：

- #12 尝试修复下
- #9 没必要的话就 close as not planned
- 更新 Makefile，定义宏来编译 latex 文件，简化规则
- 更新 README，添加一般的编译方式，因为大部分 Windows 用户可能并没有安装 Make
- 在源文件注释和手册中添加非 Windows 用户安装所需字体的方法，latex 包里的字体缺少某些字符，比如`沄`
- #13 如其所言，`figure/` 目录混杂了不同用处的图片，如果论文中包含大量图片就会造成混乱，我建议分为以下三个目录：
  - `template/`：用于该模板本身的图片
  - `thesis/`：用于论文的图片，也即手册中使用的图片
  - `slides/`：用于 PPT 的图片（但感觉先将 PPT 拆分出去比较好

**Comment by Zewbiee** [comment]
> 我列了下我想进行的更新，麻烦学长看下哪些可以进行：
> 
> * [[BUG] 任务书自动生成的参考文献内容可能会被遮挡 #12](https://github.com/zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system/issues/12) 尝试修复下
> * [源文件中的缩进存在 tab 和空格混用的情况 #9](https://github.com/zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system/issues/9) 没必要的话就 close as not planned
> * 更新 Makefile，定义宏来编译 latex 文件，简化规则
> * 更新 README，添加一般的编译方式，因为大部分 Windows 用户可能并没有安装 Make
> * 在源文件注释和手册中添加非 Windows 用户安装所需字体的方法，latex 包里的字体缺少某些字符，比如`沄`
> * [提几点模板的调整/优化建议( 对应版本v0.1.0, 2023.3.20) #13](https://github.com/zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system/issues/13) 如其所言，`figure/` 目录混杂了不同用处的图片，如果论文中包含大量图片就会造成混乱，我建议分为以下三个目录：
>   
>   * `template/`：用于该模板本身的图片
>   * `thesis/`：用于论文的图片，也即手册中使用的图片
>   * `slides/`：用于 PPT 的图片（但感觉先将 PPT 拆分出去比较好

我觉得都挺好的，包括 #6 也可以考虑做一个选项，选择题目只占一行时是否显示第二条横线。

**Comment by Zewbiee** [comment]
如果你有兴趣的话，也可以现在创一个专用账号接着做，因为我做的话可能还要等到不知道什么时候。

**Comment by jaxvanyang** [comment]
> 我觉得都挺好的，包括 #6 也可以考虑做一个选项，选择题目只占一行时是否显示第二条横线。

主要是学校给的模板就有两行线，不清楚老师会不会挑这方面的刺，我先 reopen，但是先不实现。

> 如果你有兴趣的话，也可以现在创一个专用账号接着做，因为我做的话可能还要等到不知道什么时候。

可以考虑 GitHub 组织，并不需要重新申请新的账号，并且可以同时存在多位管理员，我觉得是比专用个人账号更好的方式。ok 的话我现在就可以创建一个叫 CSUST LaTeX SIG 的组织，然后拉学长进来。

**Comment by Zewbiee** [comment]
> 可以考虑 GitHub 组织，并不需要重新申请新的账号，并且可以同时存在多位管理员，我觉得是比专用个人账号更好的方式。ok 的话我现在就可以创建一个叫 CSUST LaTeX SIG 的组织，然后拉学长进来。

可以的

**Comment by jaxvanyang** [comment]
> > 可以考虑 GitHub 组织，并不需要重新申请新的账号，并且可以同时存在多位管理员，我觉得是比专用个人账号更好的方式。ok 的话我现在就可以创建一个叫 CSUST LaTeX SIG 的组织，然后拉学长进来。
> 
> 可以的

![image](https://github.com/zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system/assets/25650612/1a117191-1392-4ec8-b534-7b3e4721b507)

需要填写联系邮箱，还是学长来创建比较好，因为我以后可能不太会用到 latex 了。

**Comment by jaxvanyang** [comment]
> 需要填写联系邮箱，还是学长来创建比较好，因为我以后可能不太会用到 latex 了。

貌似只是用来发账单的，那我可以创建一下。

**Comment by jaxvanyang** [comment]
已发送邀请 @zb-zombie

**Comment by jaxvanyang** [comment]
学长可以把这个仓库 transfer 到 @csust-latex-sig ，所有的 issue 都会保留。

**Comment by jaxvanyang** [comment]
@Postroggy 有兴趣加入吗？
